soft_reset_halt
armv4_5 core_state arm
mww 0xffffff60 0x00320100
mww 0xfffffd44 0xa0008000
mww 0xfffffc20 0xa0000601
sleep 100
mww 0xfffffc2c 0x00480a0e
sleep 200
mww 0xfffffc30 0x7
sleep 100
mww 0xfffffd08 0xa5000401
set remote memory-write-packet-size 1024
set remote memory-write-packet-size fixed
set remote memory-read-packet-size 1024
set remote memory-read-packet-size fixed
mww 0xfffffd00 0xa5000004
mww 0xffffff00 0x01
reg pc 0x00000000
arm7_9 sw_bkpts enable
